spring:
  application:
    name: ismp-template
  zipkin:
    base-url: http://localhost:6907
  sleuth:
    sampler:
      percentage: 1.0
  #连接redis数据库的配置  
  redis:
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6706
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器连接密码（默认为空）
    password: 
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 300
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 10
      # 连接池中的最小空闲连接
      min-idle: 0
      test-on-create: false
      test-on-borrow: true
      test-on-return: false
      test-while-idle: true
    # 连接超时时间（毫秒）
    timeout: 5000
#mysql connection
  datasource: 
    url: jdbc:mysql://localhost:3306/ismp_resource?characterEncoding=utf8&useSSL=false
    username: kedacom
    password: kedacom@123
    driverClassName: com.mysql.jdbc.Driver
    
#指定xml映射文件的路径  
mybatis: 
  mapper-locations: classpath:mapper/*.xml    
    
ismp:
  datasource:
    resource:
      url: jdbc:mysql://172.16.248.71:3306/ismp_resource?useUnicode=true&characterEncoding=UTF8&useSSL=false
      username: kedacom
      password: kedacom@123
      driverClassName: com.mysql.jdbc.Driver
    
server:
    port: 6920   #启动端口


#消息队列服务器(MQ)连接信息
mq:
    type: kafka
    host: localhost
    port: 6703
    address: ${mq.host}:${mq.port}
    
eureka:
    instance:
    #statusPageUrlPath: ${management.context-path}/info
    #healthCheckUrlPath: ${management.context-path}/health
        leaseRenewalIntervalInSeconds: 1
        leaseExpirationDurationInSeconds: 2 
        statusPageUrlPath: /info
        healthCheckUrlPath: /health
        ##防止多网卡识别错误
        prefer-ip-address: true
        ip-address: 127.0.0.1
        metadataMap:
            modelName: 资源管理服务
            typeName: 基础服务层
            versionNum: 1.0.0
            publishTime: 2018-4-13
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://ismp:ismp@localhost:6900/eureka/